volumes:
  postgres_data:

services:
  postgres:
    image: postgres:16.3-alpine
    container_name: postgres
    env_file: .env
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5454:5432"